version: 2.1
orbs:
  slack: circleci/slack@4.10.1
jobs:
#  notify:
#    docker:
#      - image  'cimg/base:stable'
#    steps:
#      - slack/notify:
#          custom: |
#            {
#              "blocks": [
#                {
#                  "type": "section",
#                  "fields": [
#                    {
#                      "type": "plain_text",
#                      "text": "*This is a text notification*",
#                      "emoji": true
#                    }
#                  ]
#                }
#              ]
#            }
#          event: always
  build:
    docker:
      - image: cimg/node:16.16

    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run: |
          node --version
          java --version
          google-chrome --version

workflows:
  build_and_deploy:
    jobs:
      - build
#    send-notification:
#      jobs:
#        - notify:
#            context: slack-secrets