orbs:
  slack: circleci/slack@4.10.1
version: 2.1
executors:
  app-executor:
    docker:
      - image: cimg/node:16.16
    working_directory: ~/project
  slack-executor:
    docker:
      - image: 'cimg/base:stable'
    resource_class: small
aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &show-node-version
    run: node --version
  - &restore-cache
    restore_cache:
      keys:
        - app-{‌{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{‌{ checksum "package.json" }}
  - &build-project
    run:
      name: Build Project
      command: |
        npm install
        npm run build
        cd dist
        zip ../dist.zip -r * .[^.]*
        echo "Build successful"
jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *show-node-version
      - *restore-cache
      - *install-dependencies
      - *save-cache

  deploy-to-digitalocean:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *build-project

  test:
    executor: app-executor
    steps:
      - run: echo "test my app"
      - slack/notify:
          event: fail
          template: basic_fail_1

      - slack/notify:
          event: always
          template: success_tagged_deploy_1

workflows:
  build_and_deploy:
    jobs:
      - test:
          context: slack-secrets
