orbs:
  slack: circleci/slack@4.10.1
version: 2.1
executors:
  app-executor:
    docker:
      - image: cimg/node:16.16
    working_directory: ~/project
  slack-executor:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small
aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &show-node-version
    run: node --version
  - &restore-cache
    restore_cache:
      keys:
        - app-{‌{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{‌{ checksum "package.json" }}
  - &build-project
    run:
      name: Build Project
      command: |
        npm install
        npm run build
        cd dist
        zip ../dist.zip -r * .[^.]*
        echo "Build successful"
jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *show-node-version
      - *restore-cache
      - *install-dependencies
      - *save-cache

  deploy-to-digitalocean:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *build-project

  notify-via-slack:
    executor: slack-executor
    steps:
      - slack/notify:
          message: "${CIRCLE_BRANCH} branch deployment to Digital Ocean is complete."
          webhook: $CIRCLECI_SLACK_WEBHOOK
      - slack/status:
          webhook: $CIRCLECI_SLACK_WEBHOOK

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-digitalocean:
          requires:
            - build
      - notify-via-slack:
          context:
            - slack
          requires:
            - build_and_deploy