name: View Secrets Values

on: [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"
          echo "secrets.SSH_DIR: $secrets.SSH_DIR"
          echo ${{secrets.SSH_DIR}} | sed 's/./& /g'